### ISSUE TITLE
Roadmap for 0.6.0

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#87]
Before start working on 0.6.0, I want to complete some pending stuff:

- [x] ~Complete PHP targets (not included in 0.6.0)~
- [x] Stabilize and fix C++ target and make it work with GC instead of ARC (for the moment) even if slow
- [x] Perform some cleanups, remove old stuff and perform some target unifications
- [X] Complete AS3 (Adobe Air for mature iOS target)
- [x] Update documentation + videotutorials showing how to use jtransc

**Comment by intrigus** [comment]
I'm working on integrating boehm gc.

**Comment by soywiz** [comment]
I have implemented a typer to avoid casts for ASM backend. Still not fully optimized, since it will work better with a SSA form, but already improves a lot static targets in some small methods:

Before:
```
C:\Users\soywiz\projects\kor\jtransc\benchmark>..\gradlew rund
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE
:startScripts UP-TO-DATE
:distTar UP-TO-DATE
:distZip UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build UP-TO-DATE
:runD
SyncVfsFile(AccessSyncVfs(com.jtransc.vfs._LocalVfs@3800fb71, C:/Users/soywiz/projects/kor/jtransc/benchmark/build/jtransc-d), '')
C:\D\dmd2\windows\bin\dmd.exe -release -O C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.d
Execute command C:\D\dmd2\windows\bin\dmd.exe -release -O C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.d
Execute command C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.exe
JTransc 0.5.16 - drunD
Java 1.8.0_51 - 25.51-b03 - 1.8.0_51-b16
Benchmarking:
plain loops...3.0078
call static mult...30.0486
call instance mult...28.0707
call instance div...106.2825
instanceof classes...180.4823
write byte[]...53.1389
write short[]...62.1656
write char[]...57.1492
write int[]...59.1596
write float[]...57.155
write double[]...80.21250000000001
String Builder 1...106.2781
String Builder 2...61.1653
long arithmetic...1.0029
simd mutable...185.4951
simd immutable...1197.1813
simd mutable matrix mult...512.3615
StringBuilder1...182.461
StringBuilder2...173.4606
Create Instances1...109.3195
Create Instances2...125.3038
Create Instances with builder...1030.709
Java's CRC32...136.3767
jzlib's CRC32...144.3838
compress java's Deflate...76.2008
compress jzlib...81.2752

BUILD SUCCESSFUL
```

After:

```:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE
:startScripts
:distTar
:distZip
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build
:runD
SyncVfsFile(AccessSyncVfs(com.jtransc.vfs._LocalVfs@682ce6b9, C:/Users/soywiz/projects/kor/jtransc/benchmark/build/jtransc-d), '')
C:\D\dmd2\windows\bin\dmd.exe -release -O C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.d
Execute command C:\D\dmd2\windows\bin\dmd.exe -release -O C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.d
Execute command C:\Users\soywiz\projects\kor\jtransc\benchmark\build\jtransc-d\program.exe
JTransc 0.5.16 - drunD
Java 1.8.0_51 - 25.51-b03 - 1.8.0_51-b16
Benchmarking:
plain loops...3.0384
                                                                                               call static mult...29.0771
call instance mult...28.0998
call instance div...105.28
instanceof classes...179.4773
write byte[]...9.023
write short[]...20.0829
write char[]...12.032
write int[]...13.0326
write float[]...20.057
write double[]...39.0964
String Builder 1...105.2797
String Builder 2...61.162
long arithmetic...0.9708
simd mutable...181.5132
simd immutable...1140.0322
simd mutable matrix mult...363.9969
StringBuilder1...166.4429
StringBuilder2...172.4584
Create Instances1...109.2903
Create Instances2...107.285
Create Instances with builder...1009.6838
Java's CRC32...134.3568
jzlib's CRC32...136.3629
compress java's Deflate...51.1667
compress jzlib...50.1329

BUILD SUCCESSFUL
```

Still fixing some issues but will come probably today. This will improve both: compilation time (less casts) and execution time (casts are really expensive) in all static targets: Haxe, D, C++, C# and AS3 for the moment.

In `write primtype[]` you can see an improvement of one order of magnitude because in those methods I was able to do casts properly without the SSA yet.
